parameters:
  - name: SNYK_TOKEN # name of the parameter; required
    type: string # data type of the parameter; required
  - name: working_directory
    type: string
    default: "."

jobs:
  - job: Snyk
    steps:
      - task: CmdLine@2
        displayName: "Install Snyc CLI"
        inputs:
          script: |
            curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
            chmod +x ./snyk
            mv ./snyk /usr/local/bin/
      - task: CmdLine@2
        displayName: "Scan Terraform files"
        inputs:
          script: snyk config set api=${{ parameters.SNYK_TOKEN }}
      - task: CmdLine@2
        displayName: "Scan Terraform files"
        inputs:
          script: |
            snyk iac test ${{ parameters.working_directory }} --sarif
            snyk iac test ${{ parameters.working_directory }} --sarif > $(Build.ArtifactStagingDirectory)/snyk-iac.sarif || true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/snyk-iac.sarif"
          ArtifactName: "CodeAnalysisLogs"
          publishLocation: "Container"
