parameters:
  - name: trivyVersion
    default: 0.45.0
  - name: working_directory
    default: .

jobs:
  - job: Trivy
    steps:
      - task: CmdLine@2
        displayName: "Download and Install Trivy vulnerability scanner"
        inputs:
          script: |
            sudo apt-get install rpm
            wget https://github.com/aquasecurity/trivy/releases/download/v${{ parameters.trivyVersion }}/trivy_${{ parameters.trivyVersion }}_Linux-64bit.deb
            sudo dpkg -i trivy_${{ parameters.trivyVersion }}_Linux-64bit.deb
            trivy -v
      - task: CmdLine@2
        displayName: "Trivy vulnerability scanner in IaC mode"
        inputs:
          script: |
            trivy config --exit-code 0 --format sarif ${{ parameters.working_directory }} > $(Build.ArtifactStagingDirectory)/trivy-results.sarif
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/trivy-results.sarif"
          ArtifactName: "CodeAnalysisLogs"
          publishLocation: "Container"
