name: Synk scan

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: CmdLine@2
    displayName: "Install Snyc CLI"
    inputs:
      script: |
       curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
       chmod +x ./snyk
       mv ./snyk /usr/local/bin/
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'snyk config set api=$(SNYK_TOKEN)'
  - task: Bash@3
    displayName: "Scan Terraform files"
    inputs:
      script: |
        snyk iac test --sarif
        snyk iac test --sarif > $(Build.ArtifactStagingDirectory)/snyk-iac.sarif || true 
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/snyk-iac.sarif'
      ArtifactName: 'CodeAnalysisLogs'
      publishLocation: 'Container'

