# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Bash@3
    displayName: 'Install terrascan'
    inputs:
      targetType: 'inline'
      script: |
        sudo apt-get update
        sudo apt-get install terrascan      

  - task: Bash@3
    displayName: 'Downloads the latest policies'
    inputs:
      targetType: 'inline'
      script: |
        terrascan init
  - task: Bash@3
    continueOnError: true
    displayName: 'Downloads the latest policies'
    inputs:
      targetType: 'inline'
      script: |
        terrascan scan -t azure -f *.tf -o sarif > results.sarif
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'results.sarif'
      ArtifactName: 'CodeAnalysisLogs'
      publishLocation: 'Container'

