name: IaC scans

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".ado/**"
      - "README.md"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkov:
    uses: 0GiS0/scan-tf-vulnerabilities/.github/workflows/checkov.yaml@main
  trivy:
    uses: 0GiS0/scan-tf-vulnerabilities/.github/workflows/trivy.yaml@main
  terrascan:
    uses: 0GiS0/scan-tf-vulnerabilities/.github/workflows/terrascan.yaml@main
  snyk:
    uses: 0GiS0/scan-tf-vulnerabilities/.github/workflows/snyk.yaml@main
